### ISSUE TITLE
Method to clear chosen key

### ISSUE THREAD

**Issue by emce** [orhanobut/hawk#1]
There is a method to clear storage, it would be fine to have `Hawk.clear(key);`

**Comment by orhanobut** [comment]
I totally agree. Instead of clear, I think "delete" signature will be convenient.

Hawk.delete(key)

**Comment by emce** [comment]
LGTM

**Comment by orhanobut** [comment]
Hawk.remove(key) is added in v1.1.  In order to have the consistency, I kept the "remove" name.
