### ISSUE TITLE
Parser interface has friend access and is not public in 1.19 . README is outdated

### ISSUE THREAD

**Issue by HoodVinci** [orhanobut/hawk#102]
HawkBuilder provides a setParser method. which takes a class implementing Parser  But the interface parser is not public.  So we can't use the method.

**Comment by HoodVinci** [comment]
Correction it's ok with current master but not with gradle import . 
dependencies {
  compile 'com.github.orhanobut:hawk:1.19'
}
Sorry for not checking before creating the issue.

**Comment by orhanobut** [comment]
Thanks for the notifying me, I was going to check this issue along with others.

**Comment by HoodVinci** [comment]
No worries . By the way there is an issue with list and maps 
    keyClassName = list.get(0).getClass().getName();
if we have a list B and C which inherits from A . The type for the list is determined by first item.  
I will try to fix and make a pull request

**Comment by orhanobut** [comment]
Closing this issue. Parser is public in the newest version.
