### ISSUE TITLE
NPE in AesCbcWithIntegrity.decrypt()

### ISSUE THREAD

**Issue by carlonzo** [orhanobut/hawk#103]
Hi,
I am working on a NPE we have been reported. hopefully someone can give us some help understanding what is happening.

here is the stackTrace:
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'javax.crypto.SecretKey com.b.a.f.b()' on a null object reference
	at com.orhanobut.hawk.AesCbcWithIntegrity.decrypt(SourceFile:368)
	at com.orhanobut.hawk.AesEncryption.decrypt(SourceFile:63)
	at com.orhanobut.hawk.Hawk.get(SourceFile:128)
	at com.orhanobut.hawk.Hawk.get(SourceFile:151)
	at com.app.android.SecureStorage.getToken(SourceFile:84)
```

the crash refers to the version 1.18 and the NPE happens when `secretKeys.getIntegrityKey()` is executed but `secretKeys` is null.

we are using `EncryptionMethod.HIGHEST`. 
thanks for your help!

**Comment by carlonzo** [comment]
I have just seen this report closed https://github.com/orhanobut/hawk/issues/39

**Comment by orhanobut** [comment]
Let me check this issue as well. A couple of issues are also waiting to be fixed. I'll do all together or any help would be appreciated as well.

**Comment by carlonzo** [comment]
thanks for your quick response. reading the issue #39 I realised that is possible that I could have a race condition between the call init(..) and the build completed.

can I suggest to consider the possibility to add a public state of hawk? a simple boolean or a more complex state in this case would have helped to avoid the call of the `get` when hawk is not ready.

**Comment by carlonzo** [comment]
I am thinking about creating a small PR about keeping an internal state of Hawk (as suggested in my previous comment) and so it can avoid access to the Storage if it's not ready. and also it can give info to the user about the status of Hawk.
I don't want to waste my/your time on it so I would ask your feedback before to start. thanks!

**Comment by orhanobut** [comment]
@carlonzo That would be great. I don't see any disadvantage of having this feature.

**Comment by carlonzo** [comment]
fixed by https://github.com/orhanobut/hawk/pull/110
