### ISSUE TITLE
 Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=683 (# cursors opened by this proc=683)

### ISSUE THREAD

**Issue by beiliubei** [orhanobut/hawk#108]
when I call function “Hawk.contains()” crash

**Comment by beiliubei** [comment]
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                             java.lang.Throwable: Explicit termination method 'close' not called

use StrictMode

**Comment by orhanobut** [comment]
I'm out of city currently, I'll check this issue in a few days

**Comment by orhanobut** [comment]
Closing this one since Sqlite is not longer supported.
