### ISSUE TITLE
Putting a list to hawk in an activity and get it in another activity

### ISSUE THREAD

**Issue by imdatcandan** [orhanobut/hawk#109]
Hi Orhan Abi,
Is it possible to put a list to hawk in an activity and get it in another activity by setting SQLite storage? To do it, should I initiliaze hawk in application class or where? Can it be a solution instead of using passing data between activities?

**Comment by orhanobut** [comment]
I'm out of city currently, I'll check this issue in a few days

**Comment by imdatcandan** [comment]
Ok, we can talk about it on Sunday :D

**Comment by mblcdr** [comment]
Yes, that is possible.
Initialize Hawk in your application class. (This step is required for using Hawk, no matter how you want to use it.)
This could be a solution for passing data between activities, however not the most efficient one.

**Comment by imdatcandan** [comment]
Thanks for your answer, a few days ago I got the solution from Hawk but I forgot to close the issue :)

**Comment by orhanobut** [comment]
@mblcdr Thanks for helping out
