### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by wangbourne** [orhanobut/hawk#112]
error message:

Error:Execution failed for task ':androidFF:dexDebug'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by orhanobut** [comment]
Are you sure it happens because of Hawk? Cannot determine the exact error really, could you provide the full stacktrace?

**Comment by wangbourne** [comment]
yes, i'm quite sure. If i remove the hawk from my project, it will be OK.  
Honestly, there's no more info(full track). From above message, it seems that it's a dependency duplication issue.

**Comment by orhanobut** [comment]
I really don't know what causes this problem, did you have any previous version? The only thing I can suggest which probably you already did clean/delete build folder and sync again.

**Comment by fncapps** [comment]
I'm having the same issue. If I remove Hawk dependency everything works fine

**Comment by orhanobut** [comment]
This issue still happens?

**Comment by orhanobut** [comment]
Closing this issue, I think it's not an issue anymore.
