### ISSUE TITLE
Hawk & ProGuard

### ISSUE THREAD

**Issue by LinkOut** [orhanobut/hawk#114]
Seems not to work well, using proguard. I've red the readme docs and set up those lines in my proguard rules. But it seem not to initialize

What i am doing is:

```java
Hawk.init(this)
                .setStorage(HawkBuilder.newSharedPrefStorage(this))
                .setEncryptionMethod(HawkBuilder.EncryptionMethod.MEDIUM)
                .setLogLevel(LogLevel.FULL)
                .setCallback(new HawkBuilder.Callback() {
                    @Override
                    public void onSuccess() {
                        EventBus.getDefault().postSticky(new HawkReady());
                    }

                    @Override
                    public void onFail(Exception e) {
                        //Toast.makeText(getApplicationContext(), "DEV - Hawk Init Failed", Toast.LENGTH_SHORT).show();
                    }
                })
                .build();
```

**Comment by mblcdr** [comment]
Are you using Hawk to persist your own classes?
Hawk uses GSON for serializing of complex data types. So you have to add Proguard rules for GSON.

```
-keepattributes Signature
-keep class sun.misc.Unsafe { *; }
```

And also for your model and event classes. Something like this:
```
-keep class com.example.app.model.** { *; }
-keep class com.example.app.event.** { *; }
```

**Comment by LinkOut** [comment]
Hi, thanks for the answer. 
I'm not using Hawk to persist classes, actually only Primitive data types.

My rules for GSON are:

'''
-keep class com.google.gson.** { *; }
-keepattributes Signature 
'''

I do also have: -keep class sun.misc.Unsafe { *; }

**Comment by mblcdr** [comment]
Are you sure that the ```onSuccess()``` method is not getting called? Maybe it's getting called and there's something wrong with the event that is emitting?

If that is not the case, can you please provide a sample project with the issue, so that we can take a look.

**Comment by LinkOut** [comment]
onSuccess() callback is called, as you can see i am sending an "Event" that Some activity handles, this is ok when i compile the app in debug & release without the proguard. But when its compiled with proguard, that event is not sent wich means onSuccess() is not called.

I will invesigate more on the issue, and if i dont find a solution i will make a sample project showing the issue.

Thanks your help.

**Comment by mblcdr** [comment]
I suspect that Proguard is messing with your event class. Try and exclude your events completely from Proguard as I suggested earlier:
```
-keep class com.example.app.event.** { *; }
```

Also make sure you have the proguard settings for EventBus which is:
```
-keepclassmembers class ** {
    public void onEvent*(**);
}
```

You can also try and toast something in the ```onSuccess()``` to make sure that it is getting called in your release version.

**Comment by LinkOut** [comment]
You are right. The problem was due to a class used and obfuscated. 

Thanks a lot for your help!
