### ISSUE TITLE
Initialization not asynchronous

### ISSUE THREAD

**Issue by fcouceiro** [orhanobut/hawk#117]
I'm initializing Hawk in a class thats not an activity, so I'm passing in Context and a callback to be called after a few more operations are done. Have a look:

     Hawk.init(context)
                .setEncryptionMethod(HawkBuilder.EncryptionMethod.HIGHEST)
                .setPassword(StorageKeys.ENCRYPT_SECRET)
                .setStorage(HawkBuilder.newSqliteStorage(context))
                .setLogLevel(LogLevel.FULL)
                .setCallback(new HawkBuilder.Callback() {
                    @Override
                    public void onSuccess() {
                        //inflateUserProgress();
                        callback.onSuccess();
                    }

                    @Override
                    public void onFail(Exception e) {
                        callback.onFail(e);
                    }
                })
                .build();

The thing is that I've an indeterminate ProgressBar in a splash activity and the onSuccess callback is hiding it. After the call to Hawk init the main thread freezes and than onSuccess is called and the progress bar hides successfully. So it's not being initialized async. 

Thanks for the library. I like the pattern being used and its flexibility!

**Comment by orhanobut** [comment]
There was a change for the callback and it actually puts the execution into the looper queue, it has been made for a request and I also think that we need to make it a real asynchronous. I'll check it and put a fix for this.

**Comment by fcouceiro** [comment]
Thanks @orhanobut ! 
Is there any harm if I run the sync init in an async task as a temporary fix?

**Comment by orhanobut** [comment]
no, it will work perfectly

**Comment by fcouceiro** [comment]
Yap! Working! Thanks

**Comment by orhanobut** [comment]
I added a different approach for the async operation. setCallback is removed but now you can use 
```java
build(callback)
```

**Comment by fcouceiro** [comment]
Thanks. I'll leave as it is, but in future implementations will surely try this one.
