### ISSUE TITLE
Why Hawk can't get List<CategoryItem>? but it can do for List<String> 

### ISSUE THREAD

**Issue by imdatcandan** [orhanobut/hawk#120]
Hi Orhan Abi,
Why Hawk can't get List< CategoryItem >, it can do for List< String > ? Do you have any idea?
This is my main problem on Hawk, if I can do this, I promise that I will close all issues which I opened otherwise I will be crazy :)
If you wanna explain, I can send the project.

 Hawk.init(this)
                .setEncryptionMethod(HawkBuilder.EncryptionMethod.NO_ENCRYPTION)
                .setStorage(HawkBuilder.newSqliteStorage(this))
                .build();

private List< CategoryItem > categoryItemList = new ArrayList< CategoryItem >();
private List< String > categoryList = new ArrayList<>();

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
//THİS İS NOT WORKİNG
        if (Hawk.contains("categoryItemList")) {
            categoryItemList = Hawk.get("categoryItemList");
        } else {
            categoryItemList.add(new CategoryItem("ayşe", "fatma"));
            categoryItemList.add(new CategoryItem("ali", "akif"));
        }
//THİS İS WORKİNG
        if (Hawk.contains("categoryList")) {
            categoryList = Hawk.get("categoryList");
        } else {
            //Category List
            categoryList.add("Favourites");
            categoryList.add("Emails");
            categoryList.add("Banking");
            categoryList.add("My info");
        }
    }

public class CategoryItem{

    private String title;
    private String text;

    public CategoryItem(String title, String text) {
        this.title = title;
        this.text = text;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
}

**Comment by imdatcandan** [comment]
I solved the problem with different approach without Hawk.

**Comment by orhanobut** [comment]
How did you solve? As a matter of fact, it should work like this out of box.
