### ISSUE TITLE
Error:(49, 13) Failed to resolve: com.github.orhanobut:hawk:1.21

### ISSUE THREAD

**Issue by anvesh523** [orhanobut/hawk#121]

**Comment by anvesh523** [comment]
compile 'com.orhanobut:hawk:1.18' ->  this dependency is working ... But not above one ...

**Comment by orhanobut** [comment]
Let me check from my side.

**Comment by anvesh523** [comment]
Ok,

**Comment by anvesh523** [comment]
Did you checked it out ?

**Comment by JoanZapata** [comment]
@anvesh523 You forgot to put ` maven { url "https://jitpack.io" }` in your repositories.

**Comment by anvesh523** [comment]
I am using gradle dependency. Is it necessary to add maven ( I don't know about maven ) ? @JoanZapata

**Comment by JoanZapata** [comment]
Most libraries you're using are actually hosted on a maven repository called "maven central".

`maven { url "https://jitpack.io" }` just adds a new maven repository (jitpack) to look for dependencies. Hawk 1.18 can only be found on jitpack so yes, it is necessary.

**Comment by anvesh523** [comment]
Ok, Thank you @JoanZapata  I will check it once.

**Comment by orhanobut** [comment]
Hawk is moved to maven central for the new versions. Closing this one.
