### ISSUE TITLE
backup database.

### ISSUE THREAD

**Issue by MRezaNasirloo** [orhanobut/hawk#124]
Hi, great job.

I was wondering is it possible to backup database and then reuse it? I'm planning to back the database file to cloud...

**Comment by orhanobut** [comment]
Hawk uses shared preferences or sqlite in behind, they are no different than regular files. You can use the same solution to backup for other sqlite or sharedpref backups.

**Comment by Pedramrn** [comment]
Thank you, however I'm concern about the key. If the key is changed during a fresh install, the backup database file with old key would be useless, hence I need to backup the key.
 So how can I get the key?

**Comment by orhanobut** [comment]
For the clarifications, which key are you referring?

**Comment by Pedramrn** [comment]
Hawk uses [java-aes-crypto](https://github.com/tozny/java-aes-crypto), there is a need for a key to encrypting and decrypting any data. I assume Hawk stores it in SharedPref or SQLite after `Hawk.init()` for later use, am I correct?

**Comment by orhanobut** [comment]
Hawk uses facebook-conceal for the underlying crypto since version 2. Therefore this issue no longer valid. Closing this one.
