### ISSUE TITLE
Is the key of the key-value pair also stored encrypted like the value?

### ISSUE THREAD

**Issue by amritbhandari** [orhanobut/hawk#126]

**Comment by orhanobut** [comment]
no, key is plain text. I don't think it's necessary to keep it encrypted since you have control on it.

**Comment by amritbhandari** [comment]
thanks for the clarification.
in my paranoid mind, i was thinking if someone does get hold of preference xml, having an encrypted key will slow them a bit. it wont be easy to guess what the encrypted value used for.

thanks.

**Comment by orhanobut** [comment]
just a quick suggestion, if you are using fixed keys, you could use something random for the value of the key, for example. 

```java
String KEY_USERNAME = "adsfsdaf234kajsfljkasd"; 
```

Even someone checks the xml file, they won't understand anything. The value is still readable for you by the variable name.

**Comment by amritbhandari** [comment]
just proves one can make simple things overtly complex.
thanks, your solution is simple and elegant.
