### ISSUE TITLE
Why frequent java.lang.IllegalStateExceptions?

### ISSUE THREAD

**Issue by baoxiehao** [orhanobut/hawk#130]
The log:

02-22 20:46:16.985 E/[bao] Provider( 3601): java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
02-22 20:46:16.985 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:677)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:752)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1603)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at com.orhanobut.hawk.SqliteStorage$SqliteHelper.put(SqliteStorage.java:98)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at com.orhanobut.hawk.SqliteStorage.put(SqliteStorage.java:26)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at com.orhanobut.hawk.Hawk.put(Hawk.java:59)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at com.orhanobut.hawk.Hawk$1.call(Hawk.java:74)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at com.orhanobut.hawk.Hawk$1.call(Hawk.java:70)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at rx.Observable.unsafeSubscribe(Observable.java:8098)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-22 20:46:16.985 E/[bao] Provider( 3601):     at java.lang.Thread.run(Thread.java:841)

02-22 20:46:21.575 E/[bao] Provider( 3601): java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.yekong.androidsupport/databases/Hawk
02-22 20:46:21.575 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1657)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1603)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at com.orhanobut.hawk.SqliteStorage$SqliteHelper.put(SqliteStorage.java:98)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at com.orhanobut.hawk.SqliteStorage.put(SqliteStorage.java:26)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at com.orhanobut.hawk.Hawk.put(Hawk.java:59)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at com.orhanobut.hawk.Hawk$1.call(Hawk.java:74)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at com.orhanobut.hawk.Hawk$1.call(Hawk.java:70)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at rx.Observable.unsafeSubscribe(Observable.java:8098)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-22 20:46:21.575 E/[bao] Provider( 3601):     at java.lang.Thread.run(Thread.java:841)

My code:

1) parse each line of file and parse the url

``` java
RssReader.parse(url)
                                        .subscribeOn(Schedulers.io())
                                        .map(new Func1<RssHandler, RssFeed>() {
                                            @Override
                                            public RssFeed call(RssHandler rssHandler) {
                                                Logger.d(TAG, String.format("parseRssFeed: url=%s, size=%d", url, rssHandler.getFeed().entries.size()));
                                                return rssHandler.getFeed();
                                            }
                                        })
                                        .doOnNext(new Action1<RssFeed>() {
                                            @Override
                                            public void call(RssFeed rssFeed) {
                                                Provider.getInstance(context).saveRssFeed(rssFeed);
                                            }
                                        }))
```

2) the saving code

``` java
    public void saveRssFeed(final RssFeed rssFeed) {
        Hawk.putObservable("feed" + rssFeed.link.hashCode(), rssFeed)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Action1<Boolean>() {
                    @Override
                    public void call(Boolean aBoolean) {
                        Logger.d(TAG, String.format("saveRssFeed: title=%s, size=%d, result=%s",
                                rssFeed.title, rssFeed.entries.size(), aBoolean));
                    }
                }, new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        Logger.e(TAG, String.format("saveRssFeed error: title=%s", rssFeed.title), throwable);
                    }
                });
    }
```

There are about 40 lines of urls, and each time the app boots up they will be parsed and maybe two exceptions listed as above. Do you known if I miss something? Thank you for your time.

**Comment by ZeDzislaw** [comment]
Same problem here.

**Comment by orhanobut** [comment]
Sqlite is not supported in new versions, unfortunately can't maintain it. Threfore closing this one.
