### ISSUE TITLE
Why libcore.io.ErrnoException?

### ISSUE THREAD

**Issue by zmingchun** [orhanobut/hawk#133]
**Hi, I meet some trouble like below,and has nothing to do with , could you help me ?**

`libcore.io.ErrnoException
read failed: EINVAL (Invalid argument)
java.security.ProviderException:Couldn't read 20 random bytes
org.apache.harmony.security.provider.crypto.SHA1PRNG_SecureRandomImpl.getRandomBytes(SHA1PRNG_SecureRandomImpl.java:559)
......
cause by:
libcore.io.ErrnoException:read failed: EINVAL (Invalid argument)
libcore.io.Posix.readBytes(Native Method)
libcore.io.Posix.read(Posix.java:128)
libcore.io.BlockGuardOs.read(BlockGuardOs.java:149)
libcore.io.IoBridge.read(IoBridge.java:445)
java.io.FileInputStream.read(FileInputStream.java:179)
libcore.io.Streams.readFully(Streams.java:81)
org.apache.harmony.security.provider.crypto.SHA1PRNG_SecureRandomImpl.getRandomBytes(SHA1PRNG_SecureRandomImpl.java:556)
org.apache.harmony.security.provider.crypto.SHA1PRNG_SecureRandomImpl.engineNextBytes(SHA1PRNG_SecureRandomImpl.java:300)
java.security.SecureRandom.nextBytes(SecureRandom.java:270)
com.orhanobut.hawk.AesCbcWithIntegrity.a(AesCbcWithIntegrity.java:222)
com.orhanobut.hawk.AesCbcWithIntegrity.c(AesCbcWithIntegrity.java:215)
com.orhanobut.hawk.AesCbcWithIntegrity.a(AesCbcWithIntegrity.java:289)
com.orhanobut.hawk.a.a(AesEncryption.java:45)
com.orhanobut.hawk.g.a(Hawk.java:101)
com.orhanobut.hawk.g.a(Hawk.java:53)
com.htmm.owner.activity.main.MainActivity$4.onLocationSuccess(MainActivity.java:234)
com.ht.baselib.helper.LbsHelper$MyLocationListener.onReceiveLocation(LbsHelper.java:113)
com.baidu.location.g.b(Unknown Source)
com.baidu.location.g.a(Unknown Source)
com.baidu.location.g$a.handleMessage(Unknown Source)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:136)
android.app.ActivityThread.main(ActivityThread.java:5135)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
dalvik.system.NativeStart.main(Native Method)
`

**Comment by orhanobut** [comment]
Hawk 2 uses facebook conceal. This shouldn't be an issue in there. It seems it's missing some core libraries that is used.
