### ISSUE TITLE
Question: get is cached with SharedPref...

### ISSUE THREAD

**Issue by Rainer-Lang** [orhanobut/hawk#134]
@orhanobut In a former issue you wrote that the result of `get` in combination of SharedPref is cached.
How can I do this in the simpliest way with using a db?
Could I use rxjava and `cache` to achieve this?

Suggestion: Maybe it's possible to write about this in the readme?

**Comment by kibotu** [comment]
you could always have some sort of wrapper around it: 

https://github.com/kibotu/common.android.utils/blob/develop/common-android-utils/src/main/java/com/common/android/utils/storage/CachedHawkValue.java 

which is helpful if you want to use encryption and have to read often
