### ISSUE TITLE
Custom Encryption

### ISSUE THREAD

**Issue by hatpick** [orhanobut/hawk#137]
Hello,

Is it possible to use a custom encryption algorithm? If yes, How?

Thanks,

**Comment by orhanobut** [comment]
Hi, 

Currently no, the interface is actually ready for custom encryption but there is a few small coupling with the current encryption. I'll open encryption and encoding API as well in order to have custom implementation

**Comment by sarn** [comment]
It's possible to have your custom encryption by implementing the public Encryption interface. I added the #193 pull request to have a public interface

**Comment by orhanobut** [comment]
PR is merged, I'll release the change with version 2.1.0.
