### ISSUE TITLE
Could not HEAD 'https://jitpack.io/com/github/orhanobut/hawk/1.22/hawk-1.22.aar

### ISSUE THREAD

**Issue by waniolka** [orhanobut/hawk#139]
I've just cloned my project repo to second PC, run Android Studio and beeing trying to Gradle sync. Gradle console returns: 
`Gradle sync failed: Could not HEAD 'https://jitpack.io/com/github/orhanobut/hawk/1.22/hawk-1.22.aar'. Received status code 524 from server: Origin Time-out`
Is there any problem with your repo at JitPack?
Logger which I'm also using syncs correctly.

**Comment by orhanobut** [comment]
It seems the problem is with jitpack at that moment, can you try again?

**Comment by waniolka** [comment]
Yeap, jitpack had some issues for about ~4 hours.
