### ISSUE TITLE
Observable operations are eagerly evaluated incorrectly

### ISSUE THREAD

**Issue by pakoito** [orhanobut/hawk#149]
The contract for Observables states that the operation has to be kicked in every time it's subscribed, once per subscription, and only at subscription time.

The current implementation using Observable.create() launches the operations once when the observable is created, and the result is shared/repeated for every subscriber.

If you don't take my word and prefer a blog post: http://artemzin.com/blog/rxjava-defer-execution-of-function-via-fromcallable/

**Comment by orhanobut** [comment]
Had a few issues back then with the first version of Hawk which used to support Rx. Due to maintain and some other reasons, I had to remove Rx support with the new version . Therefore closing this issue.  

But thank for the explanation though. Definitely noted that. 👍
