### ISSUE TITLE
l got a nullException when l get a long data

### ISSUE THREAD

**Issue by klower1989** [orhanobut/hawk#154]
l got a nullPointException when l get a long data:
 long lastTime = Hawk.get(JsConstant.KEY_EXPIRETIME);

then l got a nullException when l get a long data

**Comment by Aetherna** [comment]
You are trying to assign null to primitive. 
Easiest recommendation: use get(key, DEFAULT_VALUE) to defend against key not found.

**Comment by orhanobut** [comment]
Hawk infers the type and it can be null. You may need to avoid using primitive type.
