### ISSUE TITLE
Not working for Android N

### ISSUE THREAD

**Issue by pedronveloso** [orhanobut/hawk#155]
When updating devices to Android N, preview 4, the library ceases to be able to write to preferences.

Upon starting the app I get this message:

```
E/System:  ********** PLEASE READ ************ 
E/System:  * 
E/System:  * New versions of the Android SDK no longer support the Crypto provider.
E/System:  * If your app was relying on setSeed() to derive keys from strings, you
E/System:  * should switch to using SecretKeySpec to load raw key bytes directly OR
E/System:  * use a real key derivation function (KDF). See advice here : 
E/System:  * https://stackoverflow.com/questions/13433529/android-4-2-broke-my-encrypt-decrypt-code-and-the-provided-solutions-dont-work 
E/System:  ***********************************
```

I'm using `HawkBuilder.EncryptionMethod.MEDIUM` and saving it to SharedPreferences.

**Comment by pedronveloso** [comment]
I believe this could related to this issue: http://android-developers.blogspot.com/2016/06/security-crypto-provider-deprecated-in.html

What I'm thinking now is, probably this will require adaptation to the new APIs. What would be the best way to migrate the existing data though?

**Comment by pedronveloso** [comment]
Here's what I'm doing currently, if anyone is interested:

When the app starts, after initializing Hawk, I check if I can set an existing key to a new value. If it can, it gets reset to the previous value, otherwise, I do this:

```
Hawk.clear()
Hawk.resetCrypto()

// Initialize Hawk again after
```

**Comment by orhanobut** [comment]
Sorry for not being responsive. is this still an issue or still using work around? I'd be happy to work on it or request for a help.

**Comment by orhanobut** [comment]
This issue seems related to the older version, closing this one for now since new version uses a different encryption library to handle. Cheers
