### ISSUE TITLE
Hawk 2 Specs

### ISSUE THREAD

**Issue by orhanobut** [orhanobut/hawk#156]
## The goal

CRUD one object in secure way and super fast.

> Hawk should do only and only one thing and it should do it best.
### Known Issues
- Startup time is quite long and this creates frictions
- Selecting right encryption option is complex, Strong, medium, no encryption etc creates confusion.
- Some devices don't have required encryption packages
- Serialization/Deserialization problems. Usually object is saved but .get() function returns null. 
- Performance issues
- Singleton
### Hawk 2.0
- [x] Use only one mode as default. Fast and secure persistency.
- [x] Reduce the startup time, therefore users won't need async operation for initialization. Better, find a way to remove init operation. 
- [x] Reduce the time for the CRUD operations. Async operation should be only used for very big data. 
- [x] Async utility is up to the client, therefore everything should be sync
- [x] Use only one storage provider and keep it pluggable. Currently sqlite and sharedpreferences are both supported but Hawk should not be used for a lot of data already. Most probably only sharedpref will be supported as built-in.
- [ ] Hawk.init() should be optional. 
- [x] Provide pluggable logger abstraction. Implementation should be up to client. Therefore remove LogLevel
- [x] Remove chain option. 
- [x] Provide pluggable storage.
- [x] Provide pluggable converter

``` java
// Initialization
Hawk.init(context);

// Save any data
Hawk.put(key, T);

// Get the original data
T t = Hawk.get(key);

// Delete 
Hawk.delete(key);

// Contains
boolean value = Hawk.contains(key);

// Total count
int count = Hawk.count();

// Delete all entries
Hawk.deleteAll();

// intercept logs
Hawk.init(context).interceptLog(new LogInterceptor(){
   @Override public void onLog(String message){
    }
});

// plug converter
Hawk.init(context).addConverter(new YourCustomConverter());

// plug storage
Hawk.init(context).addStorage(new YourCustomStorage());


```

**Comment by Rainer-Lang** [comment]
suggestions:

- method isInitialized()

- caching

**Comment by Rainer-Lang** [comment]
Information: RxJava and usage of ```Observable.create()``` or ```Single.create()```:
Till now you are using ```Observable.create()```, but there are different known issues. Have a look here:
https://artemzin.com/blog/rxjava-defer-execution-of-function-via-fromcallable/
and http://blog.danlew.net/2015/07/23/deferring-observable-code-until-subscription-in-rxjava/

Please also use ```Single``` -> http://reactivex.io/documentation/single.html

**Comment by orhanobut** [comment]
@Rainer-Lang I am going to remove Rx support. The goal of hawk 2 is to reduce the scope as much as possible in order to maintain it easily. There are many things actually will be removed as well

**Comment by Rainer-Lang** [comment]
@orhanobut Thanks for the information. I think this decision wasn't so easy. ;)
When v2 is out I have to look how to integrate it (RxJava).

**Comment by pedronveloso** [comment]
@orhanobut Will the data from `1.23` migrate automatically?

**Comment by orhanobut** [comment]
@pedronveloso Unfortunately no, I'm thinking an additional migrate tool but most probably it's not gonna happen.

**Comment by pedronveloso** [comment]
@orhanobut I would ask then if the new Hawk could have a different package, so both the new version and the old one can live in the same project, which should make it easier for the developers to write their own migrations.

**Comment by orhanobut** [comment]
@pedronveloso I actually thought about Hawk2 naming but then realized it would be too ugly. But in this case I might change the first option perhaps. HawkDeprecated would be super good convention :)

**Comment by pedronveloso** [comment]
@orhanobut I've no stronger opinion towards one or the other, but for example Square increments the number of the library `retrofit` -> `retrofit2` , and that seems to be a trend so you might take that into consideration.
I can write a sample migration example for the repo if you'd like, once you've decided the different naming.

**Comment by Rainer-Lang** [comment]
@orhanobut Is it in this state of development possible to say something about performance between v1 and v2 (init, write, read)?

**Comment by orhanobut** [comment]
@Rainer-Lang I didn't do any benchmark test but new version is faster (especially for init). This is one of the reason that I switched to conceal.

**Comment by JordyLangen** [comment]
Will it be possible to migrate from Hawk v1 to Hawk v2 in a production app?

**Comment by Rainer-Lang** [comment]
@JordyLangen Did you figure something out?

**Comment by JordyLangen** [comment]
@Rainer-Lang did not had the chance to look into, we never migrated

**Comment by luaz** [comment]
Since Hawk and Hawk2 have exactly the same package name, it's safe to say migration shall be impossible (since can't run Hawk to retrieve the value and store as Hawk2)?

**Comment by orhanobut** [comment]
Closing this one and will fix all other open issues. Thank you all.
