### ISSUE TITLE
i think Hawk.remove() should use "sql  like "

### ISSUE THREAD

**Issue by dingyong666** [orhanobut/hawk#158]
count1 = db.delete("hawk", "hawk_key=\'" + key + "\'", (String[])null);

remove() Need to know all of the key ，but we use Key name like article_{id} In the majority situation ,so Cannot be easily removed , O(∩_∩)O 在线翻译凑出来的，凑合看吧

**Comment by orhanobut** [comment]
👍 Sqlite is no longer supported in new version due to main reason. Therefore closing this issue.
