### ISSUE TITLE
Get a java.lang.IllegalStateException after calling removeAllCookie()

### ISSUE THREAD

**Issue by isiyin** [orhanobut/hawk#164]
Hi, I've  got a java.lang.IllegalStateException after calling 

> CookieManager cookieManager = CookieManager.getInstance();
>         cookieManager.removeAllCookie();`

Here is some track info:

> Caused by: java.lang.IllegalStateException: Hawk is not built. Please call build() and wait the initialisation finishes.
>                                                                               at com.orhanobut.hawk.HawkUtils.validateBuild(HawkUtils.java:28)
>                                                                               at com.orhanobut.hawk.Hawk.get(Hawk.java:98)
>                                                                               at com.orhanobut.hawk.Hawk.get(Hawk.java:128)

And When I remove the code above，the exception disappeared.
Could you please tell me why and how to solve this problem?
Looking forward to your reply. 
Best wishes.

**Comment by orhanobut** [comment]
Which version are you using?

**Comment by isiyin** [comment]
The version I'm using is v1.23 release.
I've got this exception on Android 4.3.
It's OK when I use Hawk on Android 5.0+.

**Comment by orhanobut** [comment]
I suppose this is not an issue with version 2.0. We can reopen if the issue still exists
