### ISSUE TITLE
How to use Hawk in junittest (without android environment)?

### ISSUE THREAD

**Issue by smoothdvd** [orhanobut/hawk#168]

**Comment by kibotu** [comment]
you could check on runtime if the test runner is running: 

https://github.com/kibotu/common.android.utils/blob/develop/common-android-utils/src/main/java/com/common/android/utils/extensions/JUnitExtensions.java#L16-L25

**Comment by orhanobut** [comment]
Hawk is coupled with Android unfortunately. You can either use instrumentation tests or Robolectric to work around.
