### ISSUE TITLE
 Fuzzy want to increase the delete function

### ISSUE THREAD

**Issue by snice** [orhanobut/hawk#170]
Now I have the following requirements
such as,
...
Hawk.put("getBooks-0",...);
Hawk.put("getBooks-1",...);
Hawk.put("getBooks-2",...);
Hawk.put("getBooks-3",...);
...

I want to remove by the following：

Hawk.deleteLike("getBooks");

Thank you!!

**Comment by orhanobut** [comment]
Unfortunately this is a specific use case. You can create this helper method by yourself and put the logic in behind. I don't want to increase the scope of hawk because of the maintenance cost.

```java
for (...
   String key = "getBooks-" + i;
   Hawk.delete(key);
}
```
