### ISSUE TITLE
Unable to enable UTF-8 encoding.

### ISSUE THREAD

**Issue by droidizer** [orhanobut/hawk#173]
I'm using hawk version 1.23 and I am unable to enable UTF-8 charset encoding for my calls. 

Could you please let me know how to resolve this issue?

**Comment by orhanobut** [comment]
This shouldn't an issue with 2+ version.

**Comment by ygorcesar** [comment]
> I'm using hawk version 1.23 and I am unable to enable UTF-8 charset encoding for my calls.
> 
> Could you please let me know how to resolve this issue?

Did you get solved? I'm with this problem too showing � in special characters after persist in Hawk
