### ISSUE TITLE
Crash at Hawk.init on Kotlin

### ISSUE THREAD

**Issue by esafirm** [orhanobut/hawk#175]
Android 6.0 
Emulator
Hawk 2.0.1
Always reproducible

In Kotlin using Hawk with `NoEncryption` will trigger `illegalAccessError`
```java
Hawk.init(application)
    .setEncryption(NoEncryption())
    .build()
```

```
java.lang.IllegalAccessError: Illegal class access: 'com.package.data.Preferences' attempting to access 'com.orhanobut.hawk.Encryption' (declaration of 'com.package.data.Preferences' appears in /data/app/com.package-1/base.apk)
```

This doesn't happen when i tried it in Java file within same codebase nor when i used `Hawk.init()` without `setEncryption`

It is also didn't happen with Hawk 1.x

Thank you 😄

**Comment by PieterAelse** [comment]
Having the same issue..

**Comment by dGorod** [comment]
The same for me. Also Kotlin.

**Comment by trevorwang** [comment]
I met the same issue. And I have a workaround. Create the java class as following, and then call the following class in your kotlin Class

```

public class HawkWrapper {
    public static void init(Context context) {
        NoEncryption encryption = new NoEncryption();
        Hawk.init(context).setEncryption(encryption).build();
    }
}

```

**Comment by orhanobut** [comment]
👍 I'll definitely check this issue to support Kotlin. I'll follow this issue in kotlin ticket. #211
