### ISSUE TITLE
Why the class "Encryption"  is not public?

### ISSUE THREAD

**Issue by luvictor** [orhanobut/hawk#176]
![qq 20161110172510](https://cloud.githubusercontent.com/assets/14093993/20171268/d7eb6028-a76a-11e6-9212-883f2746e018.jpg) 
I want to implement Encryption, but it's not public.

**Comment by orhanobut** [comment]
There is no reason to be honest, it should be public. I'll check the reason again and most probably I'll make it public. Thanks for the issue.

**Comment by luvictor** [comment]
![image](https://cloud.githubusercontent.com/assets/14093993/20208744/2827afea-a82b-11e6-9cf0-d9e645eea95d.png)
and ConcealEncryption

**Comment by k0mat** [comment]
I would like to add that Serializer is not public as well.

**Comment by sarn** [comment]
added a [pull request](https://github.com/orhanobut/hawk/pull/193) with a public Encryption interface

**Comment by orhanobut** [comment]
One pr is merged to enable it as public. I'll publish it with version 2.1.0
