### ISSUE TITLE
put a tree map but got a hash map

### ISSUE THREAD

**Issue by rabbitom** [orhanobut/hawk#185]
```
TreeMap<Integer,Integer> map = new TreeMap<>();
map.put(1,1);
Hawk.put("map",map);
Map<Integer,Integer> newMap = Hawk.get("map");//class of newMap is HashMap
```

[See the whole project here](https://github.com/rabbitom/hawktest)

Please try to fill all questions below before submitting an issue.

- [ ] On which android versions do you have this issue? :6.0.1
- [ ] On which phones do you have this issue? :Nexus5
- [ ] Which hawk version are you using? :2.0.1
- [ ] Does this issue happen always or is it flaky? :always
- [ ] Can you write failing test? : A created a project to reproduce this.
- [ ] If it is Hawk.put and Hawk.get issue, can you write down which data you were trying to save and get it back? a TreeMap
- [ ] Is the data you are trying to save it huge or small? small

**Comment by orhanobut** [comment]
Internally Hawk automatically uses HashMap for conversion. I can't do much about this for now to be honest.
