### ISSUE TITLE
Not save old data of previous apk when update apk.

### ISSUE THREAD

**Issue by nhhoang1811vn** [orhanobut/hawk#196]
Please try to fill all questions below before submitting an issue.

- [ ] On which android versions do you have this issue? :
- [ ] On which phones do you have this issue? :
- [ ] Which hawk version are you using? :
- [ ] Does this issue happen always or is it flaky? :
- [ ] Can you write failing test? :
- [ ] If it is Hawk.put and Hawk.get issue, can you write down which data you were trying to save and get it back?
- [ ] Is the data you are trying to save it huge or small?

**Comment by hram** [comment]
On which android versions do you have this issue?
After OS update from android 6 to 7

On which phones do you have this issue? 
- Galaxy S6 Edge (zerolte)
- Galaxy A5(2016) (a5xelte)
- Galaxy Note5 (noblelte)
- Galaxy S6 Edge (zerolte)
- Galaxy A3(2016) (a3xelte)

Which hawk version are you using?
1.23

Does this issue happen always or is it flaky?
always after OS update 

Can you write failing test? 
no

if it is Hawk.put and Hawk.get
Hawk.put("SOME_KEY", 0L) return false and if i reed this property Hawk.get("SOME_KEY", 0L) I receive old value

Is the data you are trying to save it huge or small?
small

How can I fix that?

**Comment by nhhoang1811vn** [comment]
Sorry @harm, Just a mistake in my code. sorry for raise this bug. And i confirm, HAWK have no this issues. :) Many Thanks
