### ISSUE TITLE
Encryption interface is not public

### ISSUE THREAD

**Issue by TooLazyy** [orhanobut/hawk#199]
Hi. I've tried to implement encryption in hawk 2.+ version but it seems to be impossible because Encryption (which is required for setEncryption() method) is not public and cannot be accessed outside the package. So i cant implement my own encryption.
Ofc i can download your project and so on.
Can you make Encryption interface public?

**Comment by AlgirdasPundzius** [comment]
+1

**Comment by trevorwang** [comment]
+1

**Comment by trevorwang** [comment]
#193

**Comment by orhanobut** [comment]
I am not sure why it wasn't public in the first place to be honest. I just merged a PR related to this and it'll be available with the upcoming version. 2.1.0

**Comment by TooLazyy** [comment]
Cool!
