### ISSUE TITLE
Multiple Hawk instances

### ISSUE THREAD

**Issue by bosgood** [orhanobut/hawk#24]
First of all, great start to this library- I sense a real need for a solid encrypted key/value store in the Android ecosystem.

I'm working on a use case that requires a set of encrypted stores, where one is semi-secure (encrypted by a secret in the app binary) and another is encrypted using a value inputted from the user. Hawk has most of the features I need but I think its singleton nature is a limitation here.

Some ideas:
* Add a [public constructor](https://github.com/orhanobut/hawk/blob/master/hawk/src/main/java/com/orhanobut/hawk/Hawk.java#L22) to Hawk
* All [`Hawk.java` getter/setter methods](https://github.com/orhanobut/hawk/blob/master/hawk/src/main/java/com/orhanobut/hawk/Hawk.java#L58) become instance methods

Questions for you:
* Do you still see the need for a singleton instance of Hawk? Is it good enough to let users create one with `new Hawk()` and manage that object themselves? Or maybe have 1 global instance (`Hawk.getInstance()`) as well as a public constructor?
* [Logger](https://github.com/orhanobut/hawk/blob/master/hawk/src/main/java/com/orhanobut/hawk/Logger.java) becomes an issue if Hawk is no longer a singleton, because the `Logger` instance must be passed down the object hierarchy.

I've already started some of this, but was interested in your feedback.

**Comment by orhanobut** [comment]
@bosgood First of all thank you for the feedback but I disagree with making hawk to enable having multiple instances for the following reasons.
- I aim to have a simple but also a strong structure. I also like to follow [Poka-Yoke](http://en.wikipedia.org/wiki/Poka-yoke) Making Hawk to have multiple instances will may let the user to make mistakes. 
- It will be error-prone to differentiate instances for the user. 
- I also don't see any reason to why not use only one instance which is current. Differentiate comes with the key already. 
- Hawk.init is already a cost (generating key), creating multiple instances would cost us more. 
- Hawk should be initialized in one place and be used everywhere by not having worried about which instance or not. 
- As you mentioned as well, we also need to change the whole structure for this feature which I don't want to do that really.

For your example. I think there is no reason to not use the same instance for storing semi/full encrypted data. Having multiple instances won't make any difference I believe.

**Comment by bosgood** [comment]
The focus on keeping the library simple is admirable. For the sake of completing the thought, here's the use case I had in mind:

```java
// An instance of Hawk that the app creates with a key that's
// provided by the app using Hawk at compile time, or
// maybe a device-specific ID.
Hawk semiSecretStorage = new Hawk("constant-random-app-key");

// Get some value that's only sort of secret, but would be useful
// to display on an account page, etc.
String accountNumberLastFour = semiSecretStorage.get(KEY_ACCOUNT_ABBREVIATION);

// An instance of Hawk that stores info that's only retrievable
// with the user's explicit permission, like an account number
// or login credentials.
Hawk secretStorage = new Hawk("user-provided-key");

// Get some object info object that was encrypted using a secret
// the app has as well as a user-provided value
Credentials userAccount = secretStorage.get(KEY_ACCOUNT_CREDENTIALS);
```

This is very similar in design to the `SharedPreferences` API. Through [`Context.getSharedPreferences(String, int)`](https://developer.android.com/reference/android/content/Context.html#getSharedPreferences(java.lang.String, int)), the class allows consumers to access multiple references that access either the same or different data depending on which `name` is provided. Hawk takes advantage of this feature this feature via the two [TAG](https://github.com/orhanobut/hawk/blob/master/hawk/src/main/java/com/orhanobut/hawk/Hawk.java#L51) and [TAG_CRYPTO](https://github.com/orhanobut/hawk/blob/master/hawk/src/main/java/com/orhanobut/hawk/Hawk.java#L52) `SharedPreferenceStorage` instances, so the ability to distinguish between one storage instance and another is definitely useful in some cases.

I'm not going to ask you to change something you don't want to, but I thought it was worthwhile to present the entire idea here just in case :) Thanks!

**Comment by LiushuiXiaoxia** [comment]
我认为有必要提供多个对象，赞成bosgood 观点。

比如的一个App是账号登录的，Hawk可以帮助我们存储一些账户的配置信息。但是如果有多个用户切换登录，则需要为每个用户配置一个Hawk。

建议改成下面的形式
```
 Hawk.storage = new SharedPreferencesStorage(appContext, accountId + TAG);
```

详细代码：
```
public static void init(Context context, String password, LogLevel logLevel) {
        Context appContext = context.getApplicationContext();
        Hawk.logLevel = logLevel;
        Hawk.storage = new SharedPreferencesStorage(appContext, TAG);
        Hawk.encryption = new AesEncryption(new SharedPreferencesStorage(appContext, TAG_CRYPTO), password);
        Hawk.encoder = new HawkEncoder(encryption, new GsonParser(new Gson()));
    }
```

```
    public static Hawk newInstance(Context context,String name,String password, LogLevel logLevel) {
        Context appContext = context.getApplicationContext();

        Hawk hawk = new Hawk();

        hawk.logLevel = logLevel;
        hawk.storage = new SharedPreferencesStorage(appContext, name + TAG);
        hawk.encryption = new AesEncryption(new SharedPreferencesStorage(appContext, TAG_CRYPTO), password);
        hawk.encoder = new HawkEncoder(encryption, new GsonParser(new Gson()));

        return hawk;
    }
```

**Comment by bosgood** [comment]
@LiushuiXiaoxia 谢谢你的意见！为了原作者的方便，我提供一下翻译：

Here's a translation for convenience:

> I think there's need to provide mutiple instances, I support bosgood's viewpoint.

> For example if an App is an account login, Hawk can help us store some account details. But if there are multiple accounts that can be switched between, we'd need for each account to have its own instance of Hawk.

> I recommend changing the interface as such:
> ```java
> Hawk.storage = new SharedPreferencesStorage(appContext, accountId + TAG);
> ```
> Detailed code:

> ```java
> public static void init(Context context, String password, LogLevel logLevel) {
>     Context appContext = context.getApplicationContext();
>     Hawk.logLevel = logLevel;
>     Hawk.storage = new SharedPreferencesStorage(appContext, TAG);
>     Hawk.encryption = new AesEncryption(new SharedPreferencesStorage(appContext, TAG_CRYPTO), password);
>     Hawk.encoder = new HawkEncoder(encryption, new GsonParser(new Gson()));
> }
> ```

> ```java
> public static Hawk newInstance(Context context,String name,String password, LogLevel logLevel) {
>     Context appContext = context.getApplicationContext(); 

>     Hawk hawk = new Hawk(); 

>     hawk.logLevel = logLevel;
>     hawk.storage = new SharedPreferencesStorage(appContext, name + TAG);
>     hawk.encryption = new AesEncryption(new SharedPreferencesStorage(appContext, TAG_CRYPTO), password);
>     hawk.encoder = new HawkEncoder(encryption, new GsonParser(new Gson())); 

>     return hawk;
> }
> ```

**Comment by yekmer** [comment]
If you need another password for encryption, you can initialize static hawk instance again. But you should remember which fields have been created with which password. Because in the current version of hawk it is written to just one file. Adding multiple instance would come more complicated cases, which would break simplicity of the hawk in my opinion.

**Comment by bosgood** [comment]
* It sounds like a lot of work to manage multiple "sub-stores" via `init` each time you access a different store. The app would have to remember which mode it was in, then `init` with the correct key before using `get` or `put`.

```java
// Initialize a store to get some app-level information
Hawk.init(context, APP_PASSWORD);
String value = Hawk.get(KEY_SOME_VALUE);

// Later on, the user unlocks some part with a provided password...
Hawk.init(context, APP_PASSWORD + USER_PASSWORD);
String userValue = Hawk.get(KEY_SOME_OTHER_VALUE);

// By this point, we'd have to call `init` before getting something
// from the APP_PASSWORD store again.
```
* What about thread safety? If there is a background thread accessing stored data, there is no guarantee that between `init` and `get`, the store is initialized to the correct password.

**Comment by yekmer** [comment]
You are right for two points that you mentioned. We should find a solution for multiple init passwords. Thread safety is a complex point not easy to find a solution by the way. For now it is using SharedPreferences which is thread-safe, but the execution for encrypt, decrypt, serialization, deserialization library is not thread safe.

**Comment by orhanobut** [comment]
Hawk will not support multiple instances in order to keep the singleton structure. I'm closing this issue.

**Comment by siavashabdoli** [comment]
what is the benefit of singleton for this? in this case it's a paradigm not a useful pattern!
