### ISSUE TITLE
Disable encryption

### ISSUE THREAD

**Issue by csechuan** [orhanobut/hawk#34]
Consider an option to disable encryption? I saw an old issue with the same thought but had been disabled. I may need it because the AES encryption causing me unrecoverable error sometimes on Samsung GT-I9100G. 

Provides alternative encryption like Facebook Conceal might be a good idea.

**Comment by orhanobut** [comment]
@csechuan I couldn't have enough time to check this issue really but it seems very critical. I checked the conceal and it seems that it will solve this problem and can put a good improvement as well. I am kind of against the non-encrypted option really, but this issue will be solved as soon as possible.

**Comment by csechuan** [comment]
Second that. Conceal might be a good option then. Hope the initiation time greatly reduce with Conceal.

As for the bug, I can't simulate the problem as it happens very random, roughly 1 or 2 times out of 50 times, and on certain devices only, so far reported cases are few Samsung devices. I suggest put less priority on fixing this.

**Comment by orhanobut** [comment]
This problem is also solved with 1.8

**Comment by orhanobut** [comment]
@csechuan  disable encryption is also added with v1.10

```java
Hawk.initWithoutEncryption(context);
```
