### ISSUE TITLE
Hawk.init() calls onSuccess() for incorrect passwords.

### ISSUE THREAD

**Issue by ragunathjawahar** [orhanobut/hawk#35]
When you call `Hawk.init()` for the second time with an incorrect password, `onSuccess()` is called.

**Comment by yekmer** [comment]
It will create another key, so unSuccess is called if key creation is ok. Sending correct password is developer's responsibility

**Comment by ragunathjawahar** [comment]
@yekmer interesting. But it doesn't create another key, it replaces the existing one. Hence losing previous information.

**Comment by orhanobut** [comment]
@ragunathjawahar Hawk does not allow multiple instance, thus you must keep the same password all the time otherwise it will always replace. Hawk does not keep the password, thus it cannot match and compare for the correctness.

**Comment by ragunathjawahar** [comment]
@orhanobut Thank you for making this clear.
