### ISSUE TITLE
NPE again...

### ISSUE THREAD

**Issue by csechuan** [orhanobut/hawk#39]
Caused by: java.lang.NullPointerException
            at com.orhanobut.hawk.AesCbcWithIntegrity.decrypt(AesCbcWithIntegrity.java:368)
            at com.orhanobut.hawk.AesEncryption.decrypt(AesEncryption.java:61)
            at com.orhanobut.hawk.Hawk.get(Hawk.java:220)
            at com.orhanobut.hawk.Hawk.get(Hawk.java:237)

**Comment by orhanobut** [comment]
Do you use Hawk.init with callback or normal init?

**Comment by csechuan** [comment]
Have any other init method beside Hawk init?
I am using Hawk.init.

**Comment by orhanobut** [comment]
Hawk has a callback init function, do you use that? How do you use hawk

**Comment by csechuan** [comment]
Oh. Init with callback. And then whoever use hawk i have to check for a true flag. The flag is true if initiated by hawk callback on success.

**Comment by orhanobut** [comment]
Callback function is async, probably that's the issue you get NPE sometimes. Before using any get/put you need to wait for the complete or you can simply use without callback in order to make it sync. In that case you don't have to check any flag

**Comment by csechuan** [comment]
At first i was using the sync method. After I get a NPE error on Hawk, I tackle it with async method with flag checking. It has no problem until I use v1.8. I don't know if is related. I will fallback to use sync method and try again.

**Comment by orhanobut** [comment]
any problem so far?

**Comment by orhanobut** [comment]
I assume this problem is solved. I'll close this issue.
