### ISSUE TITLE
Editable object is not saved

### ISSUE THREAD

**Issue by tevjef** [orhanobut/hawk#41]
fixed by calling toString() on the CharSequence.

**Comment by orhanobut** [comment]
Hmm, that's interesting, can you give more details about this please? Hawk already converts everything to string at behind.

**Comment by tevjef** [comment]
It's an amateur move on my part to not call toString() after getText(). getText() on an EditText returns an Editable, which the internal json parser really hates for some reason. 

I made a test that fails :/ 

    public void testCharSequence() {
        EditText view = new EditText(context);
        view.setText("Test");
        CharSequence expected = view.getText();
        
        Hawk.put("tag", expected);
        assertEquals(expected, Hawk.get("tag"));
    }

**Comment by orhanobut** [comment]
This looks like a gson parse error instead of memory leak. The reason it fails is something that I need to check, I'm changing title to charsequence/Editable issue instead of memory leak.

**Comment by orhanobut** [comment]
Almost 3 years, closing this one since this is related to first version. We can reopen if the issue still exists. Sorry for my super late response btw.
