### ISSUE TITLE
Save heavy List freeze UI

### ISSUE THREAD

**Issue by LinkOut** [orhanobut/hawk#50]
I have a class like this:

public class TestClass {
//This got 2 Strings as property
}

Then i made a List of 8000 "TestClass" ... T
When i try to save it to Hawk it freeze the UI.

How to handle this?

Thanks!

**Comment by orhanobut** [comment]
The only solution is to use a background thread unfortunately.

**Comment by LinkOut** [comment]
Thats right, so for save and retrieve heavy Objects the AsyncTask fix the problem.

Thanks, solved.

**Comment by Rainer-Lang** [comment]
@LinkOut Or use RxJava.

**Comment by orhanobut** [comment]
I'm thinking to add rxjava support in the next milestone, then it will be supported out of box.

**Comment by LinkOut** [comment]
Actually there are several uses of the Hawk Lib. one of them is to persist "Heavy" data, avoiding the use of a DB. 

@Rainer-Lang Actually the AsyncTask fixed very well the problem. The only thing is that you need to use an observer pattern to handle when the operation of save or retrieve is done. 

In my case is not a problem since this operations are done on the SplashScreen, and actually it does not take very much time.

**Comment by Rainer-Lang** [comment]
@orhanobut WOW - very nice! :-) Thanks a lot. So I can use it in rx-chains.
