### ISSUE TITLE
Datetime issue

### ISSUE THREAD

**Issue by aligurelli** [orhanobut/hawk#52]
Hi,

Hawk does not support to save DateTime object which is made by Jodatime. Can you please fix this issue?

**Comment by orhanobut** [comment]
Apparently the problem is with the joda time object, there is a work-around for this.
https://github.com/gkopff/gson-jodatime-serialisers

With the new version, you can set the gson, that could solve the problem.
```java
.setParser(new GsonParser(gson));
```
