### ISSUE TITLE
Feature Request: method returning all key-value pairs in storage

### ISSUE THREAD

**Issue by xenurec** [orhanobut/hawk#57]
Can you implement a method **returning all key-value pairs** currently in storage?

I have just a few entries with Hawk (all wrapped as my own `SettingsItem` object) and i want to iterate over them without explicitely get every entry by key name. Something like a `getAll()`/`toArray()`/... method:

```java
Hawk.put("key1", new SettingsItem());
Hawk.put("key2", new SettingsItem());

for (Object obj : Hawk.getAll()) {
   if(obj instanceof SettingsItem) {
      // do something
   }
}
```

I hope this can help generally and not only for my problem, perhaps you have a better (more general) idea.

Thanks for this easy to implement SharedPreference solution!

**Comment by orhanobut** [comment]
That sounds good for a few items but for a large set of items, that could be a problem. In your case maybe (workaround), you can use a map to keep all your items and save it to Hawk.

For the feature, I'll think about this. Maybe with a filter option.

```java
Map<String, T> result = Hawk.filter("key").getAll();
```

**Comment by xenurec** [comment]
I'll close this. I use your idea and store all my keys in an additional map and so I can get all stored settings by one. You can easily iterate over all key-values with this "registry"-map.
