### ISSUE TITLE
Failed to resolve: com.orhanobut:hawk:1.17 

### ISSUE THREAD

**Issue by chasten** [orhanobut/hawk#58]
When I compile the library with compile 'com.orhanobut:hawk:1.17', it show the following error:
Failed to resolve: com.orhanobut:hawk:1.17 ;
What's wrong with this.

**Comment by orhanobut** [comment]
That's a mistake, the latest is 1.16

**Comment by chasten** [comment]
OK, thanks, it works fine now!
