### ISSUE TITLE
Crash on return from background

### ISSUE THREAD

**Issue by VeeruPV** [orhanobut/hawk#59]
Hi there, 
I have been having a crash when the app returns from background, specifically after a few hours. It seems Hawk instance is removed and it becomes null. Throwing exception

java.lang.NullPointerException: Attempt to invoke interface method \'java.lang.Object com.orhanobut.hawk.Storage.get(java.lang.String)\' on a null object reference
	at com.orhanobut.hawk.Hawk.get

I have tried re-initializing Hawk onResume but does'nt seem to help. 

Any suggestions?

Thanks

**Comment by yekmer** [comment]
It seems Hawk.init is not completed when you call hawk.get, you can basically put hawk.init into your Application's onCreate method, then it would not create that error. But be careful as your app created this method will be called, and it can slow your startup time, if you see a slow startup time, then decrease encryption level with the latest version of hawk

**Comment by orhanobut** [comment]
How do you init Hawk?

**Comment by VeeruPV** [comment]
The app runs fine with Hawk (so hawks init is completed). 

It only is a problem when it returns from background after a few hours; works fine if the app is in the background for a few minutes. So am assuming it has to do with android's GC, Hawk is null and crashes.


This is how i init hawk in the app's MainActivity.

Hawk.init(this, "hdsapp", new Hawk.Callback() {
                                @Override
                                public void onSuccess() {
                                    System.out.println("User id " + Hawk.get("CURRENT_USER_ID"));        
//Move on to next activity after init                           
                                }

                                @Override
                                public void onFail(Exception e) {
                                    System.out.println("Hawk fail" + e.getLocalizedMessage());
                                }
                        });

**Comment by orhanobut** [comment]
Yes, that's the exact problem, when the activities are in background for a long time, apparently OS kills all of them but still keeps a shortcut to them, even static values which Hawk uses too.

I'd suggest you to move the init to a class which extends Application, so anytime you try to open an activity from background, this will make sure that init will be called (If the states are killed), otherwise it will use the current one. 

You can also use hawk with another secure level which init is almost instant.
```java
Hawk.init(this)
    .setEncryptionMethod(HawkBuilder.EncryptionMethod.MEDIUM)
    .build()
```

**Comment by VeeruPV** [comment]
Let me try moving the initialization into Application based class like you have mentioned. I hope that helps, will only know after a little testing.  Thanks for the headups orhanobut.

**Comment by orhanobut** [comment]
I assume that problem is solved. Closing this issue

**Comment by mksharifinia** [comment]
use RunOnUiThread 

because you used background thread
