### ISSUE TITLE
Can't find some method and classes

### ISSUE THREAD

**Issue by chasten** [orhanobut/hawk#60]
I import the jar with   compile 'com.orhanobut:hawk:1.16' in Android Studio, But I can't find some methods and classes like HawkBuilder.
![Uploading 2~LPJE_{JS0TT]BH3$SHZXN.jpg…]()

**Comment by orhanobut** [comment]
I reupload the artifacts, apparently had some issues with maven central. It will be available in a few minutes with a new version v1.17
