### ISSUE TITLE
Can't get List<Foo> from Hawk.get

### ISSUE THREAD

**Issue by JChord** [orhanobut/hawk#61]
Hi there, 
I defined a Class named Foo.

    public class Foo {

        private String carSeries;
        private Uri carImageUri;
        private String carType;

        public String getCarSeries() {
            return carSeries;
        }

        public void setCarSeries(String carSeries) {
            this.carSeries = carSeries;
        }

        public Uri getCarImageUri() {
            return carImageUri;
        }

        public void setCarImageUri(Uri carImageUri) {
            this.carImageUri = carImageUri;
        }

        public String getCarType() {
            return carType;
        }

        public void setCarType(String carType) {
            this.carType = carType;
        }

        @Override
        public String toString() {
            return "Foo{" +
                "carSeries='" + carSeries + '\'' +
                ", carImageUri=" + carImageUri +
                ", carType='" + carType + '\'' +
                '}';
        }
    }

    List<Foo> foos = new ArrayList<Foo>();
    foos.add(new Foo());
    foos.add(new Foo());
    Hawk.put(Constant.PREF_FOO, foos);

but `Hawk.get(Constant.PREF_FOO, new ArrayList<Foo>());` always return list which size is 0(default value).

**Comment by LinkOut** [comment]
Hawk.get(Constant.PREF_FOO, new ArrayList<Foo>()); <- This is wrong, because the proper way to get back your "foos" is this:
List<Foo> foos = Hawk.get(Constant.PREF_FOO);

Check the doc.

**Comment by JChord** [comment]
I think it's the `Uri `class causes the Gson can't deserialize the `Foo` object.
When I removed it, it gonna be right.

**Comment by LinkOut** [comment]
hmm if i understand well you try to do something like this? 
* Hawk.get(Constant.PREF_FOO, new ArrayList()); <- get the default value
* Maybe if the default value is 0 you just "put" your foo's Hawk.put(Constant.PREF_FOO, foos);
* You try to retrieve the foos back with something like: List < Foo > foos = Hawk.get(Constant.PREF_FOO); (after you put them) and the size is 0?

**Comment by JChord** [comment]
yep, i put the list which size is 2.
The 'Url' field cause `Hawk.get` always return the 0 size list(default value).

**Comment by orhanobut** [comment]
I haven't tried yet but gson apparently can't serialize and deserialize everything due to immutability, I'll find another parse approach. I have the same problem with joda time. 

Work around could be to use transient keyword for Uri to avoid it being serialized/deserialized for now.

**Comment by LinkOut** [comment]
In alternative to GSON i recommend Jackson

**Comment by orhanobut** [comment]
I'll create another issue for different converters. I'm closing this issue.
