### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by LinkOut** [orhanobut/hawk#63]
Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

So, since i got an OOM problem with the low memory devices when try to retrieve objects i have saved to Hawk, i'm now using Sqlite option like this:
1. in my class that extends Application :         Hawk.init(this)
               .setStorage(HawkBuilder.newSqliteStorage(this))
               .setLogLevel(LogLevel.FULL)
               .build();
2. Save the objects to Hawk :  Hawk.put("a", listOfFoo);
3.   Hawk.get("a"); <- This cause that problem...

Why this? Thanks!

**Comment by LinkOut** [comment]
I think the problem in to save the String encoded to the SQLite, this String is 3131376 as count, maybe there is a limit of Sqlite? but i dont think so... Maybe i just need to find other way to save this heavy data ... 

Or maybe i can try save them "in pieces" and not all together

Any suggestions?

**Comment by orhanobut** [comment]
Hmm, how do you save them?

**Comment by LinkOut** [comment]
Like this: Hawk.put("a", mObj);

Where mObj is a HashMap<String,Object>

The problem is at line 153 of SqliteStorage.class

What i saw debugging was that you save on the SQLITE the string base64 encoded that represents the object i want to save on Hawk.

**Comment by orhanobut** [comment]
need to check sqlite thoroughly, could be a limit issue indeed

**Comment by orhanobut** [comment]
Since Sqlite is not supported with the new version, I'm closing this one.
