### ISSUE TITLE
Object with polymorphic types

### ISSUE THREAD

**Issue by LinkOut** [orhanobut/hawk#69]
I think GSON used for serializa and deserializa the objects we want to save using Hawk, got a problem with the polymorphic types.
Using Jackson there is no problem

Is there a way to let us change GSON used for parsing with other like Jackson?

Thanks.

**Comment by orhanobut** [comment]
Parser interface is public for implementation, you can implements parser and create a jackson parser and set it
```java
.setParser(new JacksonParser());
```

Let me know if it does work for you

**Comment by orhanobut** [comment]
I created an issue about parser in general. We can follow up in there. #210
