### ISSUE TITLE
can i use other json lib like fastjson?

### ISSUE THREAD

**Issue by hamberluo** [orhanobut/hawk#70]
since i have already used fastjson.

**Comment by orhanobut** [comment]
there is setParser method which accepts Parser, all you need to do is to implement Parser interface and pass it to Hawk.
```java
.setParser(new YourCustomParser())
```

**Comment by hamberluo** [comment]
if i use custom parser, how can i remove the gson dependency?
because i don't want to increase my app code methods.

thanks~

**Comment by orhanobut** [comment]
Next version I'll do it optional dependency, since there are others who wants to use different parser as well

**Comment by Rainer-Lang** [comment]
@orhanobut So it would be also possible to use Jackson?
Do you mean with "next version" Hawk 2.0?
