### ISSUE TITLE
Hawk should follow the common 'getInstance(...)' way of initialising and using the singleton instead of 'init(...)'

### ISSUE THREAD

**Issue by adrianchifor** [orhanobut/hawk#74]
This would change the syntax from Hawk.init(...) and Hawk.put(...) to Hawk.getInstance(...).put(...) and so on. It's a much safer way to work with singletons because we let the Hawk instance initialise itself when required, because right now if we don't call 'init' and try to call Hawk.put(...) we get a NPE. 

This also enables us to implement extra functionality like closing the instance when no longer required.

**Comment by adrianchifor** [comment]
Assign it to me, I'll do it over the weekend.

**Comment by orhanobut** [comment]
Hawk.init is a must to generate key which takes a little time and also there are many configurations, using getInstance will add extra call all the time and it is kind of against the simplicity.

There should be always a single instance but we can introduce another method to clear this instance. 
```java
Hawk.destroy(); // destroy all instances that hawk uses
```

and for the NPE, it is ugly indeed but that should throw a detailed exception which tells the user that Hawk.init must be called first.

**Comment by orhanobut** [comment]
Closing this one since no change will be done.
