### ISSUE TITLE
There should be a way of using password based encryption and not requiring to store the password variable in memory (in the HawkBuilder singleton instance)

### ISSUE THREAD

**Issue by adrianchifor** [orhanobut/hawk#75]
This could be implemented by adding functionality to the Hawk class like resetPassword() and setPassword(String) when required, that would then set the password for the HawkBuilder instance. Or maybe put/get methods that take an extra password parameter. 

This would be useful in apps that need to quickly put or get some secure info using Hawk and do not want the password used in encryption exposed to attackers (A rooted attacker could read the HawkBuilder object instance from memory and get the password variable value).

**Comment by adrianchifor** [comment]
Assign it to me, I'll do it over the weekend.

**Comment by orhanobut** [comment]
We need to consider performance, instead of calling a reset password, hawk should do that out of box in the init phase. using password to generate key is very expensive cost.

**Comment by orhanobut** [comment]
no action is taken.
