### ISSUE TITLE
Check whether there is an encrypted database present

### ISSUE THREAD

**Issue by Kisty** [orhanobut/hawk#79]
Is there a way to check very quickly if there is an encrypted database already?

**Comment by orhanobut** [comment]
```java
Hawk.count()
```

would help in this case I think, if count > 0, that means there is an encrypted data.

**Comment by Kisty** [comment]
Yeah, that should do the trick! 

Didn't need this in the end but thanks anyways :).

**Comment by orhanobut** [comment]
cheers! :)
