### ISSUE TITLE
Is storing list faster in hawk than using Shared Preference

### ISSUE THREAD

**Issue by AkshayChordiya** [orhanobut/hawk#8]
Hello,

I seem to like this library, and I got an obvious question. 

To store an ```List``` specifically ```ArrayList``` I use GSON library & then store it into the ```SharedPreference```.
While Hawk has an direct method to save a ```List``` so which would be faster ?

Thank you.

**Comment by orhanobut** [comment]
I haven't done any benchmark test really but as soon as I have time, I'd really like to make this test in the terms of speed and space. I'll keep to update this thread. But just to mention that, hawk uses encryption, that's why it is slower but I need to check exactly how exactly the difference is.

**Comment by AkshayChordiya** [comment]
Ohhkay. Thanks

**Comment by orhanobut** [comment]
@AkshayChordiya you may want to check the benchmark results that I put in readme. Currently List<T> is faster in Hawk and List<String> is slower. But those tests are not certain for every phone.

**Comment by AkshayChordiya** [comment]
@orhanobut 
Thanks, I'll take a look at them
