### ISSUE TITLE
Benchmark for SQLite?

### ISSUE THREAD

**Issue by Rainer-Lang** [orhanobut/hawk#81]

**Comment by orhanobut** [comment]
Haven't done any benchmark for SQLite yet, but will add when I have time.

**Comment by Rainer-Lang** [comment]
Background for my question: Should I use SQLite or not....

**Comment by orhanobut** [comment]
It totally depends on your needs, if you have a couple of data, sharedpref would be better choice since it cashes them after first read, but if you have a huge amount of data, you can go for sqlite.

**Comment by Rainer-Lang** [comment]
I only have one or two objects with about 10 values. So from your answer I should use SharedPref. 
Thanks.

**Comment by orhanobut** [comment]
That would be fine with sharedpref, let me know if you have performance issues please. Closing this issue for now.
