### ISSUE TITLE
Parser interface is not public

### ISSUE THREAD

**Issue by Christophe668** [orhanobut/hawk#84]
Hi Orhan,

The interface `Parser` doesn't seems to be public, for now we can't set are own Parser.
Thanks for this new 1.19 update, this library is really useful !

**Comment by orhanobut** [comment]
Thanks @Christophe668 for this good feedback, would you mind to submit a PR for this? It would be great!

**Comment by Christophe668** [comment]
Sure ! It's done :)

**Comment by orhanobut** [comment]
since we have it, I'm closing this issue. thanks
