### ISSUE TITLE
Is it possible to get the init() also with rx-support?

### ISSUE THREAD

**Issue by Rainer-Lang** [orhanobut/hawk#86]

**Comment by orhanobut** [comment]
You can definitely do that with buildRx method

**Comment by Rainer-Lang** [comment]
Thank you. Excuse me - I haven't seen it in the readme.....

**Comment by orhanobut** [comment]
It's my mistake actually, It wasn't in Readme file, I've just added it. Thank you for the issue though to realize this.

**Comment by Rainer-Lang** [comment]
:-D
