### ISSUE TITLE
How to confused Hawk?

### ISSUE THREAD

**Issue by KagayamaKaede** [orhanobut/hawk#88]
How to confused Hawk?

**Comment by orhanobut** [comment]
I didn't get the issue really? What do you mean by confused?

**Comment by KagayamaKaede** [comment]
Oh,sorry, I want to use proguard with my project,but I don't know how to write proguard code about Hawk.

**Comment by orhanobut** [comment]
Ahh, I'll add it to readme very soon.

**Comment by orhanobut** [comment]
I think following code would be enough.

```
#Gson
-keep class com.google.gson.** { *; }
-keepattributes Signature
```

**Comment by KagayamaKaede** [comment]
Thank you for reply,issue solved.

**Comment by Rainer-Lang** [comment]
@orhanobut Is it possible to write it on the readme?

**Comment by orhanobut** [comment]
@Rainer-Lang added, when I have time I'll add it as consumer, thus you won't need to add it manually

**Comment by wangbourne** [comment]
seems it related to other classes too. In my project, it came the following error when proguard is on:

:04:23.532 [ERROR] [system.err] Warning: com.orhanobut.hawk.Hawk$1: can't find superclass or interface rx.Observable$OnSubscribe
15:04:23.532 [ERROR] [system.err] Warning: com.orhanobut.hawk.Hawk$2: can't find superclass or interface rx.Observable$OnSubscribe
15:04:23.532 [ERROR] [system.err] Warning: com.orhanobut.hawk.HawkBuilder$2: can't find superclass or interface rx.functions.Func0
15:04:23.532 [ERROR] [system.err] Warning: com.orhanobut.hawk.HawkBuilder$2$1: can't find superclass or interface rx.Observable$OnSubscribe
15:04:23.820 [ERROR] [system.err] Warning: com.orhanobut.hawk.Hawk: can't find referenced class rx.Observable
15:04:23.820 [ERROR] [system.err] Warning: com.orhanobut.hawk.Hawk: can't find referenced class rx.Observable
15:04:23.820 [ERROR] [system.err] Warning: com.orhanobut.hawk.Hawk: can't find referenced class rx.Observable$OnSubscribe
15:04:23.820 [ERROR] [system.err] Warning: com.orhanobut.hawk.Hawk: can't find referenced class rx.Observable
15:04:23.820 [ERROR] [system.err] Warning: com.orhanobut.hawk.Hawk: can't find referenced class rx.Observable
