### ISSUE TITLE
Min SDK

### ISSUE THREAD

**Issue by TheFinestArtist** [orhanobut/hawk#9]
I like to know if there is any reason hawk is using min SDK as 10? Thanks!

**Comment by orhanobut** [comment]
According to the dashboard, below 10 is 0.4 percent. https://developer.android.com/about/dashboards/index.html That's why I choose 10 as minimum requirement. But if there is any usage of API 8, I might consider to check API 8 or 9.

**Comment by TheFinestArtist** [comment]
Actually, I see no reason min sdk to be 1, since it is using SharedPreferences, Gson and AES. If it's possible, I think make it low as possible might be not that bad idea!

**Comment by orhanobut** [comment]
It makes sense but gotta check thoroughly. Thanks for the feedback! :+1: I think adding min 10 comes as a reflex of using IDE but as you said if there is no specific reason, I agree it should be low.

**Comment by TheFinestArtist** [comment]
Thanks, I really love this concept. Most of my apps are using 8 or 9 for the min SDK so.. I hope I can use this library! If you want, I can make you a very nice sample app for this library!

**Comment by orhanobut** [comment]
I will certainly lower the minimum requirement as it seems there is no reason to use min 10. I'd be happy to have this sample :)

**Comment by orhanobut** [comment]
min sdk is 8 now.
