### ISSUE TITLE
Please add a version changelog

### ISSUE THREAD

**Issue by sferra** [orhanobut/hawk#95]
A changelog would be really useful to quickly determine if a new version may be used without breaking compatibility with existing code. That's why i think that the changelog should be added before such things happen.

**Comment by orhanobut** [comment]
Hi,

I always add the changes in the release notes instead of an individual readme file.

https://github.com/orhanobut/hawk/releases

**Comment by sferra** [comment]
thanks for pointing that out. i never thought to look there as i never manually download the releases but just update the version in my gradle file.
the advantage of having a changelog versioned with the project files is that the changelog would not be depending on the "releases" feature of github (which is just the platform where the project is currently hosted).
for now i know where to look, so feel free to close this issue if you wish.

**Comment by orhanobut** [comment]
Thanks for the feedback and now I see there is confusion or hidden information about the changelog when using releases section. I'll add a small information in readme to redirect people when they want to see changelog. 

Additionally, I like the idea of separating details from the project itself, I'm moving those details to either wiki or releases section for the changelog. I believe it's a good practice to keep the things where they belong. On the other hand, there is a habit or easiness of using readme files for this purpose.
