### ISSUE TITLE
Upgrading from 1.4 to 1.19

### ISSUE THREAD

**Issue by jlhp** [orhanobut/hawk#97]
I just upgraded from version 1.4 to 1.19 and found out that none of my previously stored values are accessible.

After some debugging I was able to confirm that the keys and their respective values are there, in the SharedPreferencesStorage, but for some reason they can't be decrypted, as I'm getting the log message: "MAC stored in civ does not match computed MAC.".

Previously I used to init the library using only this:

```
Hawk.init(this, getString(R.string.hawk));
```

But given that the library is using a builder to init everyhting I'm now using:

```
Hawk.init(this)
    .setEncryptionMethod(HawkBuilder.EncryptionMethod.HIGHEST)
    .setPassword(getString(R.string.hawk))
    .setStorage(HawkBuilder.newSharedPrefStorage(this))
    .setLogLevel(LogLevel.FULL)
    .build();
```

Is there any setting which I'm missing, or is there anything I can do to make sure that the library stays backward compatible?

P.S: I upgraded the library because one of my users was reporting exception: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: SecretKeyFactory,
and as I understand it has been fixed in the latest releases.

If there's anything you need from me, please let me know.

**Comment by orhanobut** [comment]
Let me check this thoroughly please. I need to confirm the tests again that it supports backward compatibility which it should.

**Comment by jlhp** [comment]
Sure, no problem please take your time.

By the way I was comparing the library changes and found out the following:

- AesEncryption initialization on 1.4, line 47 of Hawk.java 
```java
Hawk.encryption = new AesEncryption(new SharedPreferencesStorage(appContext, TAG_CRYPTO), password); // TAG_CRYPTO = "324909sdfsd98098"
```

- AesEncryption initialization on 1.19, line 176 of HawkBuilder.java
```java
encryption = new AesEncryption(getStorage(), getPassword());
public Storage getStorage() {
    if (cryptoStorage == null) {
      cryptoStorage = new SharedPreferencesStorage(context, TAG);
    }
    return cryptoStorage;
  }
```

So, maybe the problem are the TAG's being used to initialize the Storage?

**Comment by mblcdr** [comment]
@orhanobut I also updated from 1.15 to 1.19 and the values previously stored could not be retrieved... That's why I stick to 1.15 for the time being.

**Comment by topeterhonz** [comment]
It looks like the salt has been moved. Try this.



```java
public static final String LEGACY_SHARED_PREF_NAME = "324909sdfsd98098";
    public static final String CURRENT_SHARED_PREF_NAME = "HAWK";
    public static final String SHARED_PREF_SALT_KEY = "asdf3242klj";

private static void migrateHawk(Context context) {
        // Migration. Hawk has decided to move the salt to the same shared preference file
        SharedPreferences legacySharedPref = context.getSharedPreferences(LEGACY_SHARED_PREF_NAME, Context.MODE_PRIVATE);
        String legacySalt = legacySharedPref.getString(SHARED_PREF_SALT_KEY, null);

        if (legacySalt != null) {
            SharedPreferences sharedPref = context.getSharedPreferences(CURRENT_SHARED_PREF_NAME, Context.MODE_PRIVATE);
            sharedPref.edit().putString(SHARED_PREF_SALT_KEY, legacySalt).apply();
            legacySharedPref.edit().clear().apply();
        }
    }
```

**Comment by orhanobut** [comment]
Closing this issue since can't support old version unfortunately.
