### ISSUE TITLE
if I remove all db.close() statements...

### ISSUE THREAD

**Issue by Throckmortra** [orhanobut/hawk#99]
Will it break Hawk? I'm making asynchronous calls to Hawk and it's closing the connection pool out of sync which leads to pool close errors. I am a novice at SQL but wouldn't the database close itself without issue?

**Comment by orhanobut** [comment]
Sorry for the late reply, let me check this one and create some tests to cover it.

**Comment by orhanobut** [comment]
Closing this issue since Sqlite is not supported unfortunately.
